version: '3.9'

services:
  blackjack-tgbot:
    image: blackjack_bot-image
    restart: always
    container_name: python-blackjack
    working_dir: /usr/src/app/bj_21_bot
    build:
      context: .
      dockerfile: ./dockerfile
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    depends_on:
      - postgres
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        python -m alembic upgrade head
        poetry run python main.py
    network_mode: host

  postgres:
    image: postgres:alpine
    container_name: postgres-blackjack
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /usr/src/app/bj_21_bot/postgres/init:/docker-entrypoint-initdb.d
      - /usr/src/app/bj_21_bot/postgres/data:/var/lib/postgresql/data
    network_mode: host
