"""create admin table

Revision ID: 79ae3b07a903
Revises: 
Create Date: 2023-03-01 00:07:19.953590

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "79ae3b07a903"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=64), nullable=False),
        sa.Column("password", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins")
    # ### end Alembic commands ###
